# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagg', '0004_auto_20151227_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
